// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '[Supabase] Missing env vars. Ensure .env has VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY. Restart dev server after editing .env.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/** No-op lock to avoid "Lock broken by another request" / AbortError from Navigator Lock API (multi-tab conflicts) */
const noOpLock = async <R>(_name: string, _acquireTimeout: number, fn: () => Promise<R>): Promise<R> => fn();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: noOpLock,
  },
});